# Spread Sheet names
 sheetName = "ti_feeds"
 sheetNameCveIds = "CVE_ids"
 sheetNameMetaData = "RSS_feeds_meta_data"
# keywords which are need for filtering feeds.keywords should be in lowercase !!!
 keyWordsLowerCase = ["google", "microsoft", "apple", " aws ", "amazon", "kubernetes", "macos", "jsonwebtoken"," jwt ", "oauth",
             "azure","cisco","openssl","openssh","ubuntu"]


