# Spread Sheet names
 sheetName = "Ti_feeds_details"
 sheetNameCveIds = "CVE_ids"
 sheetNameMetaData = "Ti_feeds_metaData"
 sheetNameAlerts = "Alerts"
# keywords which are need for filtering feeds.keywords should be in lowercase !!!
 keyWordsLowerCase = ["google", "microsoft", "apple", " aws ", "amazon", "kubernetes", "macos", "jsonwebtoken"," jwt ", "oauth",
             "azure","cisco","openssl","openssh","ubuntu"]

refreshToken = ""
clientId = ""
clientSecret = ""
spreadSheetId = ""
mlModelBaseUrl = "http://20.94.36.14:80/api/v1/service/mlfiltering/score"
mlModelBearerToken = ""


